[phases.setup]
nixPkgs = ["dotnet-sdk_8"]

[phases.install]
cmds = ["dotnet --version", "dotnet restore"]

[phases.build]
cmds = ["dotnet publish --no-restore -c Release -o out"]

[start]
cmd = "dotnet out/IntentManagementAPI.dll"

[variables]
NIXPACKS_DOTNET_VERSION = "8.0" 