version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Intent2025!
      - MSSQL_DATABASE=IntentManagementDB
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

  intent-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8921:80"
    depends_on:
      - sqlserver
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=IntentManagementDB;User Id=sa;Password=Intent2025!;TrustServerCertificate=True;

volumes:
  sqlserver_data:
